server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: Asdb2023
    url: jdbc:postgresql://asugardbserver.postgres.database.azure.com:5432/asugar_db
    username: Asugar_db_server@asugardbserver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: agilesugar5@gmail.com
    password: fdlbggnimjamgzke

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 3000
          write timeout: 5000
